# Generated by Django 4.1.7 on 2023-05-09 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_id", models.CharField(max_length=10)),
                ("airline", models.CharField(max_length=50)),
                ("departure_date", models.DateField()),
                ("arrival_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                ("departure", models.CharField(max_length=50)),
                ("arrival", models.CharField(max_length=50)),
                ("flight_price", models.IntegerField()),
                ("seat_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="join",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
                ("passenger_id", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
                ("AID", models.IntegerField()),
                ("PID", models.IntegerField()),
                ("flight_id", models.CharField(max_length=10)),
                ("order_price", models.IntegerField()),
                ("ticket_time", models.DateTimeField(default=datetime.datetime.now)),
                ("payment_status", models.SmallIntegerField()),
                ("key", models.CharField(max_length=50)),
                ("payment_platform", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="payment_method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_platform", models.CharField(max_length=50)),
            ],
        ),
    ]
