# Generated by Django 4.1.7 on 2023-05-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="passenger_id",
            field=models.ManyToManyField(to="airline.passenger"),
        ),
        migrations.AlterModelTable(name="passenger", table="course",),
    ]
